### ISSUE TITLE
Destination with space isn't escaped properly

### ISSUE THREAD

**Issue by sjelfull** [neoziro/ssh-pool#13]
I'm trying to copy a file from remote to locally, and my destination path has spaces in it. This causes rsync to freak out and return an error.

This is my test task in shipit:

``` javascript
shipit.task('testspace', function () {
    return shipit.remoteCopy('/home/test/path/file.bz2', '/Users/fred/Projects/Path With Space/', {
      direction: 'remoteToLocal'
    });
});
```

This is the error returned by rsync:

```
rsync error: syntax or usage error (code 1) at /SourceCache/rsync/rsync-45/rsync/main.c(1166) [receiver=2.6.9]

    at ChildProcess.exithandler (child_process.js:696:12)
    at ChildProcess.EventEmitter.emit (events.js:104:17)
    at maybeClose (child_process.js:808:16)
    at Socket.<anonymous> (child_process.js:1025:11)
    at Socket.EventEmitter.emit (events.js:101:17)
    at Pipe.close (net.js:459:12)
```

Without spaces, it works just fine. I also tried to escape it manually:

```
/Users/fred/Projects/Path\ With\ Space/
```

It doesn't seem to affect ssh-pool/rsync, though:

```
Copy "host@host.com:/home/test/path/file.bz2" to "/Users/fred/Projects/Path With Space/file.bz2" via rsync
```

**Comment by gregberge** [comment]
It's not the job of this module to do that, escape them yourself:

``` js
shipit.task('testspace', function () {
    return shipit.remoteCopy('/home/test/path/file.bz2', '/Users/fred/Projects/Path\\ With\\ Space/', {
      direction: 'remoteToLocal'
    });
});
```

**Comment by sjelfull** [comment]
Ah, I thought that was just what I did. Thanks, I'll try that.

I think the module easily could be smarter about paths with spaces in them, though. If you want more people to use this, it's likely others is going to hit this problem as well.

_I realised after writing this that this comment belong on the main shipit repo._

**Comment by gregberge** [comment]
@sjelfull try to not put space in directories it's not a good practice

**Comment by briantjacobs** [comment]
@sjelfull @neoziro I also ran into this problem. Spaces within directories is not something I can avoid.

I understand that it's not the job of this module to handle escaping, but it's more that the rsync command breaks when there's spaces involved without extra quotes. The paths that worked turned out to be this:

```
this.connection.copy(
    "'/local/path/to/dir with spaces'", 
    "'/remote/path/to/dir\ with\ spaces'", 
    { rsync: ["--progress"]}
)
```
Note that both paths have extra single quotes. The local path does not want its spaces escaped, while the remote path does.

Alternatively, to avoid headaches here, this function...

```
  var cmd = ['rsync'].concat(rsyncOptions).concat([
    '-e',
    '"ssh ' + connection.sshArgs.join(' ') + '"',
    completeSrc,
    completeDest
  ]).join(' ');
```

Could be changed to this, so the user would not have to sleuth that extra single quotes are needed.

```
  var cmd = ['rsync'].concat(rsyncOptions).concat([
    '-e',
    '"ssh ' + connection.sshArgs.join(' ') + '"',
    '\''+ completeSrc+'\'' ,
    '\''+ completeDest+'\''
  ]).join(' ');
```
The result is similar to this example: http://askubuntu.com/a/597610

Either way, maybe a note in the documentation could help. Anyhow, thanks for making ssh-pool.
